repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages:
          - pre-commit
      - id: end-of-file-fixer
        stages:
          - pre-commit
      - id: check-yaml
        stages:
          - pre-commit
      - id: check-added-large-files
        stages:
          - pre-commit

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        name: lint commit messages
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        name: lint Python files
        stages:
          - pre-commit

  # FIXME: Figure a way out to make mypy work. Refer to the issue thread below for more information:
  # https://github.com/python/mypy/issues/10428
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.5.1
  #   hooks:
  #     - id: mypy
  #       name: type-check Python files
  #       stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: format Python files
        stages:
          - pre-commit

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        name: format JS/TS files
        files: \.[jt]sx?$
        types: [file]
        stages:
          - pre-commit
        additional_dependencies:
          - eslint@8
          - eslint-config-prettier
          - eslint-config-next

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: lint JS/TS files
        files: \.[jt]sx?$
        types: [file]
        stages:
          - pre-commit
        additional_dependencies:
          - prettier@3
          - "@trivago/prettier-plugin-sort-imports"
