name: Lint Commit Messages

on:
  pull_request:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  commitlint:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Setup and Run Commitlint
        uses: wagoid/commitlint-github-action@v5.4.3
