name: QA Checks

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.2

      - name: Install Pre-Commit and the Hooks
        run: |
          pipx install pre-commit
          npm install

      - name: Run the Hooks for QA Checks
        run: npm run pre-commit

  commitlint:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.2

      - name: Setup and Run Commitlint
        uses: wagoid/commitlint-github-action@v6.0.0
