name: QA Checks

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Setup Python for the Environment
        uses: actions/setup-python@v4.7.0

      - name: Setup and Run the Pre-Commit Hooks
        uses: pre-commit/action@v3.0.0

  commitlint:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Setup and Run Commitlint
        uses: wagoid/commitlint-github-action@v5.4.3
